name: py27
channels:
- conda-forge
- defaults
dependencies:
- bottleneck=1.2.0
- cloudpickle=0.2.2
- entrypoints=0.2.2
- h5py=2.6.0
- hdf5=1.8.17
- limix=1.0.12
- matplotlib=2.1.0
- numpy=1.12
- pandas=0.19.2
- pip=9.0.1
- python=2.7
- scipy=0.19.1
- scipy-sugar=1.0.4
- setuptools=27.2.0
- sphinx=1.5.1
